
name: Upload to riff raff

on:
  push:
    paths:
      - 'tags/*.json'  
    branches:
      - main 
  workflow_dispatch:  

jobs:
  tag-section-validator:
    name: Check tags and sections are valid via CAPI client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'sbt'

      - name: Run SBT project
        run: |
          export API_KEY=$API_KEY
          sbt run
        env: 
          API_KEY: ${{ secrets.CAPI_KEY }}

  validate_json:
    name: Validate JSON files in tags directory
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Validate JSON files
      run: |
        cd tag-section-validator/dist
        json_files=$(ls *.json)
        for file in $json_files; do
          echo "Validating $file"
          jq . "$file"
        done

  CI:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.4.0
          cache: 'npm'
          cache-dependency-path: 'cdk/package-lock.json'

      - name: cdk synth
        working-directory: ./cdk
        run: |
          npm ci
          npm run lint
          npm test
          npm run synth

      - uses: guardian/actions-riff-raff@v4
        with:
          app: my-guardian-suggested-tags
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          buildNumberOffset: 10
          configPath: riff-raff.yaml
          contentDirectories: |
            my-guardian-suggested-tags-cfn: 
              - cdk/cdk.out/MyGuardianSuggestedTags-CODE.template.json
              - cdk/cdk.out/MyGuardianSuggestedTags-PROD.template.json
            my-guardian-suggested-tags-static: 
              - tag-section-validator/dist