name: Validate tags/sections and upload to riff-raff

on:
  push:
    paths:
      - '*'  
    branches:
      - main 
  pull_request:
    paths:
      - 'cdk/**'
      - 'tag-section-validator/**'
    branches:
      - main
  workflow_dispatch:  

jobs:
  upload-to-riff-raff:
    name: Validate tags/sections and upload to riff-raff
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'sbt'

      - name: Run SBT project
        run: |
          cd tag-section-validator
          export API_KEY=$API_KEY
          sbt run
        env: 
          API_KEY: ${{ secrets.CAPI_KEY }}

      - name: Validate JSON files
        run: |
          cd tag-section-validator/dist
          json_files=$(ls *.json)
          for file in $json_files; do
            echo "Validating $file"
            jq . "$file"
          done

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.4.0
          cache: 'npm'
          cache-dependency-path: 'cdk/package-lock.json'

      - name: cdk synth
        working-directory: ./cdk
        run: |
          npm ci
          npm run lint
          npm test
          npm run synth

      - uses: guardian/actions-riff-raff@v4
        with:
          app: my-guardian-suggested-tags
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          buildNumberOffset: 10
          configPath: riff-raff.yaml
          contentDirectories: |
            my-guardian-suggested-tags-cfn: 
              - cdk/cdk.out/MyGuardianSuggestedTags-CODE.template.json
              - cdk/cdk.out/MyGuardianSuggestedTags-PROD.template.json
            my-guardian-suggested-tags-static: 
              - tag-section-validator/dist