
name: JSON Validation

on:
  push:
    paths:
      - 'tags/*.json'  # Trigger only when JSON files are added/modified in the "tags" directory

jobs:
  validate_json:
    name: Validate JSON files in tags directory
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Validate JSON files
      run: |
        cd tags
        json_files=$(ls *.json)
        for file in $json_files; do
          echo "Validating $file"
          jq . "$file"
        done