
name: JSON Validation

on:
  push:
    paths:
      - 'tags/*.json'  
  workflow_dispatch:  

jobs:
  validate_json:
    name: Validate JSON files in tags directory
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Validate JSON files
      run: |
        cd tags
        json_files=$(ls *.json)
        for file in $json_files; do
          echo "Validating $file"
          jq . "$file"
        done

  CI:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.4.0
          cache: 'npm'

      - name: cdk synth
        working-directory: ./cdk
        run: |
          npm ci
          npm run lint
          npm test
          npm run synth

      - uses: guardian/actions-riff-raff@v4
        with:
          app: my-guardian-suggested-tags
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          configPath: riff-raff.yaml
          contentDirectories: |
            my-guardian-suggested-tags-cfn: 
              - cdk/cdk.out/MyGuardianSuggestedTags-CODE.template.json
              - cdk/cdk.out/MyGuardianSuggestedTags-PROD.template.json
            my-guardian-suggested-tags-static: 
              - tags/dist